services:
  cf-zookeeper:
    image: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=cf-zookeeper:2888:3888
    ports:
      - "2181:2181"
    networks:
      - cloud-based-de
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 30s
      retries: 3
      start_period: 10s